blank_issues_enabled: true
contact_links:
  - name: ðŸ’¬ Join Slack
    url: 'https://docs.pydantic.dev/logfire/help/#slack'
    about: Join the Pydantic Logfire Slack to ask questions, get help and chat about Logfire
  - name: ðŸ¤” Ask a Question on GitHub Discussions
    url: 'https://github.com/pydantic/pydantic/discussions/new?category=question'
    about: Ask a question about how to use Logfire using github discussions
  - name: ðŸ“§ Email Us
    url: 'https://docs.pydantic.dev/logfire/help/#email'
    about: To contact us privately, email engineering@pydantic.dev
